# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=1024)),
                ('checkmark', models.BooleanField(default=False)),
            ],
        ),
    ]
