# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='section',
            new_name='section_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='section_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
