# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20181119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_category_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='topic_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
